# Configurações de conexão com o banco de dados
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/academy?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC

  # Configurações específicas do JPA e Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
      hibernate.ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Configurações do Thymeleaf
  thymeleaf:
    mode: HTML
    cache: false
